# Generated by Django 3.1.7 on 2021-04-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210423_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподваватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
