# Generated by Django 3.1.7 on 2021-04-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210423_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers', verbose_name='Добавить фото')),
                ('name', models.CharField(max_length=70, verbose_name='Ф.И.О')),
                ('position', models.CharField(max_length=70, verbose_name='Должность')),
                ('edu', models.TextField(verbose_name='Образоание')),
                ('experience', models.TextField(verbose_name='Трудовая деятельность')),
                ('certificates', models.TextField(verbose_name='Сертификаты')),
                ('publications', models.TextField(verbose_name='Публикации')),
                ('works', models.TextField(verbose_name='Основные работы')),
                ('contacts', models.TextField(verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Преподваватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
