# Generated by Django 3.1.7 on 2021-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210423_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers', verbose_name='Добавить фото')),
                ('name', models.CharField(max_length=70, verbose_name='Ф.И.О')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподваватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AlterModelOptions(
            name='teachersdetail',
            options={'verbose_name': 'Преподваватель (подробнее)', 'verbose_name_plural': 'Преподаватели (подробнее)'},
        ),
        migrations.AlterField(
            model_name='teachersdetail',
            name='certificates',
            field=models.CharField(max_length=70, verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='teachersdetail',
            name='edu',
            field=models.CharField(max_length=150, verbose_name='Образоание'),
        ),
        migrations.AlterField(
            model_name='teachersdetail',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
