# Generated by Django 3.1.7 on 2021-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210423_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/news', verbose_name='Добавить фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/teachers', verbose_name='Добавить фото'),
        ),
        migrations.AlterField(
            model_name='teachersdetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/teachers', verbose_name='Добавить фото'),
        ),
    ]
