# Generated by Django 3.1.7 on 2021-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210423_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students', verbose_name='Добавить фото')),
                ('name', models.CharField(max_length=150, verbose_name='Ф.И.О')),
                ('position', models.CharField(max_length=150, verbose_name='Специальность')),
                ('works', models.CharField(max_length=140, verbose_name='Работает в')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Наши выпускники',
            },
        ),
        migrations.AlterField(
            model_name='teachersdetail',
            name='contacts',
            field=models.CharField(max_length=150, verbose_name='Контакты'),
        ),
    ]
