# Generated by Django 3.1.7 on 2021-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210424_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=70, verbose_name='Телефон')),
                ('phone2', models.IntegerField(max_length=70, verbose_name='Доп. телефон')),
                ('email', models.CharField(max_length=70, verbose_name='Почта')),
                ('email2', models.CharField(max_length=70, verbose_name='Доп. почта')),
                ('adress', models.CharField(max_length=140, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
