# Generated by Django 3.1.7 on 2021-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=70, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone2',
            field=models.CharField(max_length=70, verbose_name='Доп. телефон'),
        ),
    ]
