# Generated by Django 3.1.7 on 2021-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210424_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='adress',
            field=models.TextField(max_length=140, verbose_name='Адрес'),
        ),
    ]
