# Generated by Django 3.1.7 on 2021-04-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210424_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersdetail',
            name='position',
            field=models.CharField(max_length=300, verbose_name='Должность'),
        ),
    ]
