# Generated by Django 3.0.8 on 2021-05-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210425_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedName', models.CharField(max_length=70, verbose_name='Имя')),
                ('feedPhone', models.CharField(max_length=13, verbose_name='Nелефон')),
                ('feedEmail', models.CharField(max_length=70, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
            },
        ),
    ]
