# Generated by Django 3.0.8 on 2021-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachersDetail',
        ),
        migrations.AddField(
            model_name='teacher',
            name='certificates',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contacts',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='edu',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Образоание'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='publications',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='works',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Основные работы'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feedPhone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
