# Generated by Django 3.1.7 on 2021-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210510_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='certificates',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contacts',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Образоание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Трудовая деятельность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='publications',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Публикации'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='works',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Основные работы'),
        ),
    ]
