# Generated by Django 3.1.7 on 2021-05-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210526_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='Заголовок'),
        ),
    ]
