# Generated by Django 3.1.7 on 2021-06-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210529_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Полное описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements', verbose_name='Добавить фото')),
            ],
            options={
                'verbose_name': 'Наши достижения',
                'verbose_name_plural': 'Наши достижения',
            },
        ),
    ]
