# Generated by Django 3.2 on 2021-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210606_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenklatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Название файла')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Добавить файл')),
            ],
            options={
                'verbose_name': 'Номенклатура дел',
                'verbose_name_plural': 'Номенклатура дел',
            },
        ),
    ]
