# Generated by Django 3.2 on 2021-07-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_nomenklatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name': 'Заявка обратной связи', 'verbose_name_plural': 'Заявки обратной связи'},
        ),
    ]
